// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieEntryContext))]
    [Migration("20230214070551_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.EntryResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("directorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("movieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Romantic Comedy",
                            Edited = true,
                            Rating = "PG-13",
                            Year = 2003,
                            directorName = "Donald Petrie",
                            lentTo = "",
                            movieTitle = "How To Lose A Guy In Ten Days"
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action/Adventure",
                            Edited = true,
                            Rating = "PG",
                            Year = 2017,
                            directorName = "Chris McKay",
                            lentTo = "",
                            movieTitle = "The Lego Batman Movie"
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Drama/Comedy",
                            Edited = true,
                            Rating = "PG",
                            Year = 1946,
                            directorName = "Frank Capra",
                            lentTo = "",
                            movieTitle = "It's A Wonderful Life"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
